# Generated by Django 4.0.3 on 2022-04-06 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='deliveryoptions',
            table='tb_delivery_options',
        ),
        migrations.AlterModelTable(
            name='paymentselections',
            table='tb_payment_selections',
        ),
    ]
