# Generated by Django 4.0.3 on 2022-04-10 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_deliveryoptions_table_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentSelections',
        ),
    ]
